### PR TITLE
fix(To-Do, Canvas): Delete confirmation dialogue, delete todo after confirmation

### PR DESCRIPTION
**Pull request by jiriks74**
Fixes leantime/leantime#1867
**Submitted on behalf of a third-party: @DerKamii**

- When deleting a To-Do the whole interface displayed inside the dialogue (and overflowed outside of it) instead of just the confirmation dialogue

- After confirmation the To-Do wasn't deleted

EDIT: I fixed [Canvas deletion](https://github.com/Leantime/leantime/issues/1856#issuecomment-1721846441) as well. The bug was the same problem in another file.

### CODE REVIEW

**Review by marcelfolaron — APPROVED** [review]

**Comment by jiriks74** [comment]
Looks like your test env broke:

```bash
Test  tests/Acceptance/InstallCest.php:installPageWorks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  [Facebook\WebDriver\Exception\SessionNotCreatedException] Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
```

Haven't found anything relevant to this not working in the logs

**Comment by jiriks74** [comment]
Yeah, that was a misclick - I'm on my phone. Sorry...

**Comment by marcelfolaron** [comment]
Thanks, can you resolve the conflicts?

**Comment by jiriks74** [comment]
Ok, looks lime my last commit prevents the docker container from starting. I'll look into it, don't merge yet.

**Comment by jiriks74** [comment]
So far if I start the container and modify the file, it works, but when I restart the container will not start up

**Comment by jiriks74** [comment]
Ok, it looks like my docker container was broken. Re-pulling the image and recreating the container then making the edits helped.

**Comment by jiriks74** [comment]
Sorry for the mess, had to fix the author on the merge commit for the bot not to freak out and block the pull request

**Comment by jiriks74** [comment]
@marcelfolaron I think that it's ready to be merged.

**Review by marcelfolaron — APPROVED** [review]

**Pull request merged**
