### PR TITLE
Update class.editUser.php

### PR DESCRIPTION
**Pull request by b90g**
https://github.com/Leantime/leantime/blob/4978c6a9c5ff647e15cc65b143f922b4b14f13e4/src/domain/users/controllers/class.editUser.php#L68

i changed it that way and at least now the page is loading again.

did the 2.1.8 work for anybody?

### CODE REVIEW

**Review by marcelfolaron — APPROVED** [review]

**Comment by marcelfolaron** [comment]
Thank you!

**Comment by dirkbez** [comment]
> https://github.com/Leantime/leantime/blob/4978c6a9c5ff647e15cc65b143f922b4b14f13e4/src/domain/users/controllers/class.editUser.php#L68
> 
> i changed it that way and at least now the page is loading again.
> 
> did the 2.1.8 work for anybody?

Version 2.1.8 (downloaded on 2021-12-16 from the website) still has the error.

**Comment by JorgeCarousel** [comment]
In my case using 2.1.8 the line was already that way, but I still copied and pasted it, but nothing happened, I still see a blank page when I try to edit any user.

**Comment by unknown797** [comment]
> In my case using 2.1.8 the line was already that way, but I still copied and pasted it, but nothing happened, I still see a blank page when I try to edit any user.

The solution is 'password' => ($row['password']), 

It needs that > added after =

**Pull request merged**
