### PR TITLE
Add show All  Tickets Per Project

### PR DESCRIPTION
**Pull request by davask**
Proposed solution for that ticket https://github.com/Leantime/leantime/issues/502

### CODE REVIEW

**Comment by marcelfolaron** [comment]
Awesome, I'll take a look this week. Sorry for the delay on that.

**Comment by marcelfolaron** [comment]
Hi @davask,

Thank you for your PR. I like the idea to show projects + tickets but I think the table in the current layout would get very large quite quickly. Instead I would probably group the tasks by project as it is set up on /tickets/showAll (Check the grouping options). We could still show project information in the grouped header.

Thank you

**Comment by javaindian** [comment]
Hi @marcelfolaron

Any roadmap when it could be incorporated? I couldn't find it in v2.2.

I tried to manually do this. My bad, i couldn't succeed. Hence rolled back.

Thanks

**Comment by corentiny1** [comment]
Same here, it's important to see all tasks in the same place and don't have to go through all the projects to try to get an overview. Maybe a kanban view with tasks labeled by the name of the project ?

**Comment by broskees** [comment]
I'm happy to work on this if you have an idea for implementation that works for you. @marcelfolaron

**Comment by clemrdh** [comment]
Still not implemented ? It would be very usefull

**Pull request closed without merging**
