### PR TITLE
Changes to remove dynamic properties.

### PR DESCRIPTION
**Pull request by acul009**
I tried to add some of the dynamic properties that are used to the actual class definitions.
This might not be compatible with all your supported PHP-versions.

If you tell me the lowest PHP-version you want to support, I could update the code.

### CODE REVIEW

**Comment by acul009** [comment]
If you want to continue my work, I used the following regex for most of it:

\$this->(.+) = new (.+)\(.*

and replaced it with

private $2 \$$1;

**Comment by marcelfolaron** [comment]
Thank you! We are going with the official PHP long term support cadence: https://www.php.net/supported-versions.php
So right now the lowest is 8.0 but we'll EOL that in November.

**Comment by acul009** [comment]
Wow, than I could have made some of the type definitions a bit tighter.

Would you accept pull requests which specify types on currently generic attributes?
While that might produce more visible errors, in a previous project those definitions caught some errors, that would have been devastating and helped increase code stability in the long term.

**Comment by marcelfolaron** [comment]
Yes, definitely. Tightening up types would help a lot!

**Review by marcelfolaron — APPROVED** [review]

**Comment by marcelfolaron** [comment]
Thank you so much!

**Pull request merged**
