### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shraddha761**
Readme updated with some grammar

### CODE REVIEW

**Comment by shraddha761** [comment]
@marcelfolaron please review

**Comment by marcelfolaron** [comment]
Hey, thanks for the suggestions but those are more stylistic changes and I am not sure I like the new wording. It's seems rather dry and long winded at times.

**Comment by marcelfolaron** [comment]
@gloriafolaron

**Comment by shraddha761** [comment]
@marcelfolaron is there any changes required

**Comment by marcelfolaron** [comment]
I don't think these changes make sense quite honestly. The wording is more complex than it was before and doesn't add any benefit.

**Pull request closed without merging**
