### PR TITLE
fix timezone issues on timesheet management

### PR DESCRIPTION
**Pull request by marcelfolaron**
#### Link to ticket

[Please add a link to the GitHub issue being addressed by this change.](https://github.com/Leantime/leantime/issues/2322)

#### Description

Timesheets had an issue with saving and pulling up times based on utc vs local timezone

#### Checklist

- [ x] My code passes all test cases.
- [ x] My code passes our static analysis suite.
- [ x] My code passes our continuous integration process.

If your code does not pass the requirements on the checklist, you should add a comment explaining why this change 
should be exempt from the list.

### CODE REVIEW

**Comment by lilosti** [comment]
Hi Marcel and co. 
I have tested this on our test setup, result is this: https://app.screencast.com/kGJRtn4fjsJeQ
It seems not to have fixed the issue completely..
/Line 
ITK Development 
Aarhus

**Comment by marcelfolaron** [comment]
@marcelfolaron @lilosti I just pushed an update to this patch which should hopefully fix this entirely.

**Comment by lilosti** [comment]
Hi Marcel - it seems to be working now!

**Comment by lilosti** [comment]
Hi Marcel - we have a new issue, that seems to be caused by your fixes... Timeregistrations done on the task is now shown on the wrong date in the timesheet - see video: https://app.screencast.com/e12a09b3xMpoZ

**Pull request merged**
