### PR TITLE
Sanitize language ini files & Align menu items

### PR DESCRIPTION
**Pull request by hartigdan**
I wanted the text of the vertically stacked menu items to be aligned. So I made all corresponding icons fixed width (fa-fw). While I was at it, i sanitized the language files a little.

### CODE REVIEW

**Review by BENETNATH — APPROVED** [review]
Nice work. Still some french issues in the translation.

**Comment by hartigdan** [comment]
Thank you. Unfortunately I don't have any French skills :slightly_smiling_face: Mostly just tried to fix obvious syntax errors.

**Comment by BENETNATH** [comment]
> Thank you. Unfortunately I don't have any French skills 🙂 Mostly just tried to fix obvious syntax errors.

I'm currently working on this one.

**Review by BENETNATH — CHANGES_REQUESTED** [review]
Still some things to be edited like variable that have spaces "% 4 $ s" should be "%4$s"
I saw that in french language

**Comment by hartigdan** [comment]
Well spotted, I'll update the PR this evening. :+1:

**Review by BENETNATH — APPROVED** [review]
Good

**Review by marcelfolaron — APPROVED** [review]

**Pull request merged**
