### PR TITLE
login: fix redirectUrl

### PR DESCRIPTION
**Pull request by lamping7**
See #304 

Let me know if you have an alternate approach for this that you'd prefer. I made a couple minor formatting changes as well for style consistency.

### CODE REVIEW

**Comment by lamping7** [comment]
I do not have this setup with emails and am not completely sure what you mean. Is there code you can point me to or more info on the use case example you're mentioning? 

Using the _server request_uri for this doesn't work for anyone with a sub folder path, but there may be a better solution than what I've done here.

**Comment by marcelfolaron** [comment]
Added a fix in #370 . Instead of updating redirect url inline I changed it at the top of the file where we handle the redirect logic

**Comment by lamping7** [comment]
👍🏻 Sounds good. I'll give it a try later this week. Thanks.

**Comment by lamping7** [comment]
FYI I finally upgraded to 2.1.7. The login still didn't work and I used my fix in this PR to resolve.

**Pull request closed without merging**
