### PR TITLE
a new admin menu - ui optimisation

### PR DESCRIPTION
**Pull request by carsteneu**
Changes in behaviour and ui of the admin elements - now there is a possibility to open the items in an explicit admin menu
it was somehow not logical that e.g. the user management has menuitems of a current project - this commit will change this.

### CODE REVIEW

**Comment by carsteneu** [comment]
@marcelfolaron - would you consider changes of this kind and especially these in the future or does it not fit into your ideas? Otherwise I would not submit such pull requests...

It looks like that:

screenshot-2020 10 20-15_35_50-1603200950300

**Comment by marcelfolaron** [comment]
I like that how do you get to that screen though? Clicking on the profile?

**Comment by carsteneu** [comment]
No, click on a submenu entry of the profile. If you click one of them, it will open this view.

**Comment by marcelfolaron** [comment]
Oh I see, maybe we can add a "back to project" link on the tip to make it
easier to get back?

**Comment by carsteneu** [comment]
Yeah - thats a good idea...  that can be added easely i think

**Comment by marcelfolaron** [comment]
Closing this for now, since there are multiple conflicts and a bit more work to do

**Pull request closed without merging**
